erDiagram
        DOMAIN |o--o| COLLECTION: contains
        COLLECTION }|--|{ PATH : contains
        PATH }|--|{ ARTIFACT : contains
        ARTIFACT }|--|{ UNIT : contains
        UNIT }o--o{ COMPONENT : contains
        ARTIFACT }o--o{ COMPONENT : contains
